/**
 * Skill Discovery Engine
 *
 * Maps a user's interests and natural aptitudes against structured skill
 * progressions to surface three types of recommendations:
 *
 *   1. Strong Matches  — high interest + high aptitude alignment
 *   2. Hidden Potential — high aptitude but low/no interest signal (the key insight)
 *   3. Growth Edges    — high interest but current aptitude gap
 *
 * The engine uses 11 trait dimensions scored from 8 questions. Each skill tree
 * has a hand-tuned trait profile. Recommendations are generated by computing
 * the dot product of the user's trait vector against each tree's profile,
 * split by interest vs. aptitude dimensions.
 *
 * This is not a personality test. It is a structured starting point for
 * exploration, grounded in the same dimensions that underlie the skill maps.
 */

// ---------------------------------------------------------------------------
// Traits
// ---------------------------------------------------------------------------

export type Trait =
  | "physical"
  | "creative"
  | "analytical"
  | "social"
  | "strategic"
  | "patience"
  | "competitive"
  | "expressive"
  | "technical"
  | "wellness"
  | "naturalistic";

export type TraitScores = Partial<Record<Trait, number>>;

// ---------------------------------------------------------------------------
// Questions
// ---------------------------------------------------------------------------

export interface DiscoverOption {
  id: string;
  label: string;
  /** Trait weights when this option signals interest. */
  interest: TraitScores;
  /** Trait weights when this option signals aptitude. */
  aptitude: TraitScores;
}

export interface DiscoverQuestion {
  id: string;
  title: string;
  subtitle?: string;
  type: "single" | "multi";
  maxSelections?: number;
  options: DiscoverOption[];
}

export const DISCOVER_QUESTIONS: DiscoverQuestion[] = [
  // Q1 — Interest signal: what domains attract you
  {
    id: "draws-attention",
    title: "What naturally draws your attention?",
    subtitle: "Pick up to 3",
    type: "multi",
    maxSelections: 3,
    options: [
      { id: "movement", label: "Physical movement and sports", interest: { physical: 3, competitive: 1 }, aptitude: {} },
      { id: "music", label: "Music and instruments", interest: { creative: 3, expressive: 2 }, aptitude: {} },
      { id: "food", label: "Cooking and food", interest: { creative: 2, naturalistic: 2, patience: 1 }, aptitude: {} },
      { id: "visual", label: "Visual arts and design", interest: { creative: 3, expressive: 2, patience: 1 }, aptitude: {} },
      { id: "tech", label: "Technology and coding", interest: { technical: 3, analytical: 2 }, aptitude: {} },
      { id: "writing", label: "Writing and language", interest: { expressive: 3, creative: 2 }, aptitude: {} },
      { id: "strategy", label: "Strategy and games", interest: { strategic: 3, analytical: 2, competitive: 1 }, aptitude: {} },
      { id: "wellness", label: "Health and wellness", interest: { wellness: 3, patience: 1 }, aptitude: {} },
      { id: "business", label: "Business and leadership", interest: { strategic: 2, social: 2 }, aptitude: {} },
      { id: "people", label: "Communication and relationships", interest: { social: 3, expressive: 1 }, aptitude: {} },
      { id: "nature", label: "Nature and the outdoors", interest: { naturalistic: 3, patience: 2, wellness: 1 }, aptitude: {} },
      { id: "photo", label: "Photography and film", interest: { creative: 2, technical: 2, expressive: 2 }, aptitude: {} },
    ],
  },

  // Q2 — Interest signal: how you spend unstructured time
  {
    id: "free-afternoon",
    title: "When you have a free afternoon, you're most likely to...",
    type: "single",
    options: [
      { id: "move", label: "Get outside and move", interest: { physical: 3, wellness: 1 }, aptitude: {} },
      { id: "make", label: "Make or build something", interest: { creative: 2, technical: 2 }, aptitude: {} },
      { id: "learn", label: "Read, study, or explore ideas", interest: { analytical: 2, strategic: 1 }, aptitude: {} },
      { id: "connect", label: "Connect with people", interest: { social: 3, expressive: 1 }, aptitude: {} },
      { id: "practice", label: "Practice or refine a skill you've started", interest: { patience: 3, competitive: 1 }, aptitude: {} },
    ],
  },

  // Q3 — Aptitude signal: what type of challenge energizes you
  {
    id: "challenge-type",
    title: "What type of challenge energizes you?",
    type: "single",
    options: [
      { id: "physical", label: "Physical challenges with measurable progress", interest: {}, aptitude: { physical: 3, competitive: 2 } },
      { id: "creative", label: "Creative challenges with no single right answer", interest: {}, aptitude: { creative: 3, expressive: 2 } },
      { id: "technical", label: "Technical puzzles with clear solutions", interest: {}, aptitude: { analytical: 3, technical: 2 } },
      { id: "social", label: "Social and interpersonal challenges", interest: {}, aptitude: { social: 3, expressive: 1 } },
      { id: "strategic", label: "Strategic challenges requiring long-term thinking", interest: {}, aptitude: { strategic: 3, patience: 2 } },
    ],
  },

  // Q4 — Aptitude signal: natural strengths
  {
    id: "natural-strengths",
    title: "Which of these comes most naturally to you?",
    subtitle: "Pick 2",
    type: "multi",
    maxSelections: 2,
    options: [
      { id: "coordination", label: "Physical coordination and body awareness", interest: {}, aptitude: { physical: 3 } },
      { id: "patterns", label: "Pattern recognition and analytical thinking", interest: {}, aptitude: { analytical: 3, strategic: 1 } },
      { id: "aesthetic", label: "Creative expression and aesthetic sense", interest: {}, aptitude: { creative: 3, expressive: 1 } },
      { id: "verbal", label: "Verbal communication and persuasion", interest: {}, aptitude: { social: 2, expressive: 3 } },
      { id: "detail", label: "Patience and attention to detail", interest: {}, aptitude: { patience: 3, analytical: 1 } },
      { id: "empathy", label: "Empathy and reading people", interest: {}, aptitude: { social: 3, patience: 1 } },
    ],
  },

  // Q5 — Both: learning style reveals both interest and aptitude
  {
    id: "learn-style",
    title: "How do you prefer to learn?",
    type: "single",
    options: [
      { id: "hands-on", label: "Hands-on practice with immediate feedback", interest: { physical: 1 }, aptitude: { patience: 2, competitive: 1 } },
      { id: "observe", label: "Watching experts and imitating", interest: { creative: 1 }, aptitude: { creative: 2, patience: 1 } },
      { id: "theory", label: "Reading theory first, then applying", interest: { analytical: 2 }, aptitude: { analytical: 2, strategic: 1 } },
      { id: "trial", label: "Trial and error — figure it out yourself", interest: { technical: 1 }, aptitude: { technical: 1, creative: 1, competitive: 1 } },
      { id: "group", label: "Learning alongside others", interest: { social: 2 }, aptitude: { social: 2 } },
    ],
  },

  // Q6 — Aptitude signal: relationship with competition
  {
    id: "competition",
    title: "What's your relationship with competition?",
    type: "single",
    options: [
      { id: "thrive", label: "I thrive on it — give me a scoreboard", interest: {}, aptitude: { competitive: 3 } },
      { id: "friendly", label: "I enjoy friendly competition but it's not the point", interest: {}, aptitude: { competitive: 1, social: 1 } },
      { id: "self", label: "I prefer competing with myself — personal bests", interest: {}, aptitude: { patience: 2, competitive: 1 } },
      { id: "collab", label: "I'd rather collaborate than compete", interest: {}, aptitude: { social: 2, creative: 1 } },
      { id: "avoid", label: "Competition stresses me out", interest: {}, aptitude: { wellness: 2, patience: 1, creative: 1 } },
    ],
  },

  // Q7 — Aptitude signal: what others see in you
  {
    id: "others-see",
    title: "People most often come to you for help with...",
    subtitle: "Pick 2",
    type: "multi",
    maxSelections: 2,
    options: [
      { id: "physical", label: "Physical tasks or demonstrations", interest: {}, aptitude: { physical: 3 } },
      { id: "creative", label: "Creative advice or ideas", interest: {}, aptitude: { creative: 3, expressive: 1 } },
      { id: "technical", label: "Technical problem-solving", interest: {}, aptitude: { technical: 3, analytical: 1 } },
      { id: "emotional", label: "Emotional support or listening", interest: {}, aptitude: { social: 2, patience: 2 } },
      { id: "strategic", label: "Strategic thinking or planning", interest: {}, aptitude: { strategic: 3, analytical: 1 } },
      { id: "teaching", label: "Teaching or explaining things clearly", interest: {}, aptitude: { expressive: 3, patience: 1 } },
    ],
  },

  // Q8 — Interest signal: aspirational goals
  {
    id: "six-months",
    title: "In six months, you'd love to be able to...",
    subtitle: "Pick 2",
    type: "multi",
    maxSelections: 2,
    options: [
      { id: "perform", label: "Perform a physical skill impressively well", interest: { physical: 3, competitive: 1 }, aptitude: {} },
      { id: "create", label: "Create something beautiful or meaningful", interest: { creative: 3, expressive: 1 }, aptitude: {} },
      { id: "build", label: "Build or code something functional", interest: { technical: 3, analytical: 1 }, aptitude: {} },
      { id: "communicate", label: "Communicate more effectively", interest: { social: 2, expressive: 2 }, aptitude: {} },
      { id: "understand", label: "Understand a complex domain deeply", interest: { analytical: 2, strategic: 2 }, aptitude: {} },
      { id: "lead", label: "Lead or influence others", interest: { social: 2, strategic: 2 }, aptitude: {} },
      { id: "care", label: "Take better care of yourself", interest: { wellness: 3, patience: 1 }, aptitude: {} },
    ],
  },
];

// ---------------------------------------------------------------------------
// Tree Profiles
// ---------------------------------------------------------------------------

export interface TreeProfile {
  pathId: string;
  title: string;
  domain: string;
  description: string;
  /** How much each trait matters for this skill. */
  traits: TraitScores;
  /** One-line connection statement for recommendations. */
  hook: string;
}

export const TREE_PROFILES: TreeProfile[] = [
  // ── Sports ──
  {
    pathId: "sports/tennis",
    title: "Tennis",
    domain: "Sports",
    description: "Footwork, strokes, strategy, and match play — from first rally to competitive play.",
    traits: { physical: 5, competitive: 4, strategic: 3, patience: 2 },
    hook: "Combines physical agility with tactical thinking in a way few sports match.",
  },
  {
    pathId: "sports/pickleball",
    title: "Pickleball",
    domain: "Sports",
    description: "The fastest-growing racket sport — accessible, social, and deeply strategic at higher levels.",
    traits: { physical: 4, social: 4, competitive: 3, strategic: 2 },
    hook: "Accessible entry point with surprising strategic depth and strong community.",
  },
  {
    pathId: "sports/strength-training",
    title: "Strength Training",
    domain: "Sports",
    description: "Progressive resistance training — from bodyweight fundamentals to structured programming.",
    traits: { physical: 5, patience: 4, competitive: 2, wellness: 3 },
    hook: "Highly measurable, deeply rewarding for people who value consistent progress.",
  },
  {
    pathId: "sports/running",
    title: "Running",
    domain: "Sports",
    description: "From first mile to structured training — pacing, form, and distance progression.",
    traits: { physical: 5, patience: 4, wellness: 3, competitive: 2 },
    hook: "The simplest entry point to measurable physical progression.",
  },

  // ── Creative Arts ──
  {
    pathId: "creative-arts/guitar",
    title: "Guitar",
    domain: "Creative Arts",
    description: "Chords, strumming, fingerpicking, scales, and performance — from first chord to full repertoire.",
    traits: { creative: 5, expressive: 4, patience: 4 },
    hook: "One of the most expressive instruments — and the patience to learn it pays off quickly.",
  },
  {
    pathId: "creative-arts/cooking",
    title: "Cooking",
    domain: "Creative Arts",
    description: "Knife skills, flavor building, techniques, and recipe adaptation across cuisines.",
    traits: { creative: 4, patience: 3, naturalistic: 3 },
    hook: "Creative expression you can share immediately — and it only gets more interesting with practice.",
  },
  {
    pathId: "creative-arts/photography",
    title: "Photography",
    domain: "Creative Arts",
    description: "Composition, lighting, camera mechanics, and visual storytelling.",
    traits: { creative: 4, technical: 3, patience: 3, expressive: 3 },
    hook: "Bridges technical precision and creative vision in a way that rewards both types of thinker.",
  },
  {
    pathId: "creative-arts/drawing-illustration",
    title: "Drawing & Illustration",
    domain: "Creative Arts",
    description: "Foundational drawing skills — proportion, shading, perspective, and visual communication.",
    traits: { creative: 5, patience: 4, expressive: 4 },
    hook: "The most direct form of visual expression — trainable with structured practice.",
  },
  {
    pathId: "creative-arts/writing",
    title: "Writing",
    domain: "Creative Arts",
    description: "Clarity, structure, voice, and revision — from clear sentences to compelling narrative.",
    traits: { creative: 4, expressive: 5, analytical: 3, patience: 3 },
    hook: "Where analytical thinking and creative expression converge — a rare combination.",
  },

  // ── Technology ──
  {
    pathId: "technology/python",
    title: "Python",
    domain: "Technology",
    description: "From first script to production code — syntax, OOP, testing, and data analysis.",
    traits: { technical: 5, analytical: 4, patience: 3 },
    hook: "The most approachable entry point to programming — and one of the most versatile.",
  },
  {
    pathId: "technology/javascript-typescript",
    title: "JavaScript & TypeScript",
    domain: "Technology",
    description: "Web development fundamentals — from DOM manipulation to typed full-stack applications.",
    traits: { technical: 5, analytical: 3 },
    hook: "Where technical skill meets visual creativity — build things people can see and use.",
  },
  {
    pathId: "technology/data-science",
    title: "Data Science",
    domain: "Technology",
    description: "Statistics, analysis, visualization, and machine learning — turning data into insight.",
    traits: { technical: 4, analytical: 5, patience: 3, strategic: 2 },
    hook: "For pattern-seekers who want to make sense of complexity.",
  },

  // ── Science ──
  {
    pathId: "science/chess",
    title: "Chess",
    domain: "Science",
    description: "Openings, tactics, positional play, and endgame — from first moves to competitive play.",
    traits: { strategic: 5, analytical: 5, competitive: 4, patience: 4 },
    hook: "The purest form of strategic thinking — and one of the most measurable.",
  },
  {
    pathId: "science/meditation-mindfulness",
    title: "Meditation & Mindfulness",
    domain: "Science",
    description: "Attention training, body awareness, and emotional regulation through structured practice.",
    traits: { wellness: 5, patience: 5 },
    hook: "Trains the one skill that amplifies every other skill — attention.",
  },

  // ── Business ──
  {
    pathId: "business/product-management",
    title: "Product Management",
    domain: "Business",
    description: "Discovery, prioritization, stakeholder management, and shipping — from feature to strategy.",
    traits: { strategic: 5, social: 4, analytical: 3, creative: 2 },
    hook: "Where strategic thinking meets empathy — orchestrating what gets built and why.",
  },
  {
    pathId: "business/public-speaking",
    title: "Public Speaking",
    domain: "Business",
    description: "Structure, delivery, presence, and audience connection — from nervous to compelling.",
    traits: { social: 4, expressive: 5, competitive: 2 },
    hook: "The most leveraged communication skill — and more trainable than most people think.",
  },
  {
    pathId: "business/personal-finance",
    title: "Personal Finance",
    domain: "Business",
    description: "Budgeting, investing, tax strategy, and long-term wealth building.",
    traits: { analytical: 4, strategic: 4, patience: 3 },
    hook: "Strategic, analytical, and deeply patient — the traits that matter most here are rare together.",
  },
  {
    pathId: "business/listening",
    title: "Listening",
    domain: "Business",
    description: "Active listening, empathic understanding, and conversational presence.",
    traits: { social: 5, patience: 4, wellness: 2 },
    hook: "The most underrated interpersonal skill — and the foundation for almost every other one.",
  },
];

// ---------------------------------------------------------------------------
// Scoring & Recommendations
// ---------------------------------------------------------------------------

export type RecommendationCategory =
  | "strong-match"
  | "hidden-potential"
  | "growth-edge";

export interface SkillRecommendation {
  tree: TreeProfile;
  category: RecommendationCategory;
  interestScore: number;
  aptitudeScore: number;
  totalScore: number;
  reasoning: string;
}

/** User's accumulated answers: questionId → array of selected option IDs. */
export type DiscoverAnswers = Record<string, string[]>;

interface TraitProfile {
  interest: TraitScores;
  aptitude: TraitScores;
}

function addTraits(target: TraitScores, source: TraitScores): void {
  for (const [trait, value] of Object.entries(source)) {
    const t = trait as Trait;
    target[t] = (target[t] ?? 0) + (value ?? 0);
  }
}

function dotProduct(userTraits: TraitScores, treeTraits: TraitScores): number {
  let sum = 0;
  for (const [trait, treeWeight] of Object.entries(treeTraits)) {
    const userWeight = userTraits[trait as Trait] ?? 0;
    sum += userWeight * (treeWeight ?? 0);
  }
  return sum;
}

function normalizeScores(scores: number[]): number[] {
  const max = Math.max(...scores, 1);
  return scores.map((s) => s / max);
}

/** Build a trait profile from the user's answers. */
export function buildTraitProfile(answers: DiscoverAnswers): TraitProfile {
  const interest: TraitScores = {};
  const aptitude: TraitScores = {};

  for (const question of DISCOVER_QUESTIONS) {
    const selected = answers[question.id] ?? [];
    for (const optionId of selected) {
      const option = question.options.find((o) => o.id === optionId);
      if (!option) continue;
      addTraits(interest, option.interest);
      addTraits(aptitude, option.aptitude);
    }
  }

  return { interest, aptitude };
}

/**
 * Top 2 trait names for a given trait profile, used in reasoning.
 */
function topTraits(traits: TraitScores, count: number): Trait[] {
  return Object.entries(traits)
    .filter(([, v]) => (v ?? 0) > 0)
    .sort((a, b) => (b[1] ?? 0) - (a[1] ?? 0))
    .slice(0, count)
    .map(([t]) => t as Trait);
}

import { TRAIT_DIMENSION_LABELS } from "@/lib/design-tokens";

const TRAIT_LABELS = TRAIT_DIMENSION_LABELS as Record<Trait, string>;

function buildReasoning(
  tree: TreeProfile,
  category: RecommendationCategory,
  userProfile: TraitProfile,
): string {
  const treeTopTraits = topTraits(tree.traits, 2);
  const traitNames = treeTopTraits.map((t) => TRAIT_LABELS[t]).join(" and ");

  switch (category) {
    case "strong-match":
      return `Your interests align with ${tree.title}, and your natural ${traitNames} give you a strong foundation. ${tree.hook}`;
    case "hidden-potential": {
      const userAptTop = topTraits(userProfile.aptitude, 3);
      const overlap = treeTopTraits.filter((t) => userAptTop.includes(t));
      const overlapNames = overlap.length > 0
        ? overlap.map((t) => TRAIT_LABELS[t]).join(" and ")
        : traitNames;
      return `You may not have considered ${tree.title}, but your natural ${overlapNames} are exactly what it requires. ${tree.hook}`;
    }
    case "growth-edge":
      return `You're drawn to ${tree.title}, and while it will stretch your ${traitNames}, that's what makes it a powerful growth opportunity. ${tree.hook}`;
  }
}

/**
 * Generate skill recommendations from a user's answers.
 * Returns up to 8 recommendations across all three categories.
 */
export function generateRecommendations(
  answers: DiscoverAnswers,
): SkillRecommendation[] {
  const profile = buildTraitProfile(answers);

  // Score each tree
  const scored = TREE_PROFILES.map((tree) => {
    const interestRaw = dotProduct(profile.interest, tree.traits);
    const aptitudeRaw = dotProduct(profile.aptitude, tree.traits);
    return { tree, interestRaw, aptitudeRaw };
  });

  // Normalize separately
  const interestNorm = normalizeScores(scored.map((s) => s.interestRaw));
  const aptitudeNorm = normalizeScores(scored.map((s) => s.aptitudeRaw));

  const categorized = scored.map((s, i) => {
    const interestScore = interestNorm[i];
    const aptitudeScore = aptitudeNorm[i];
    const totalScore = interestScore + aptitudeScore;

    // Thresholds for categorization
    const highInterest = interestScore > 0.55;
    const highAptitude = aptitudeScore > 0.55;

    let category: RecommendationCategory;
    if (highInterest && highAptitude) {
      category = "strong-match";
    } else if (highAptitude && !highInterest) {
      category = "hidden-potential";
    } else if (highInterest && !highAptitude) {
      category = "growth-edge";
    } else {
      category = "growth-edge"; // low on both — still include if it scores well
    }

    return {
      tree: s.tree,
      category,
      interestScore,
      aptitudeScore,
      totalScore,
      reasoning: buildReasoning(s.tree, category, profile),
    };
  });

  // Sort by total score within each category
  const strongMatches = categorized
    .filter((r) => r.category === "strong-match")
    .sort((a, b) => b.totalScore - a.totalScore)
    .slice(0, 3);

  const hiddenPotential = categorized
    .filter((r) => r.category === "hidden-potential")
    .sort((a, b) => b.aptitudeScore - a.aptitudeScore)
    .slice(0, 3);

  const growthEdges = categorized
    .filter((r) => r.category === "growth-edge")
    .sort((a, b) => b.interestScore - a.interestScore)
    .slice(0, 2);

  return [...strongMatches, ...hiddenPotential, ...growthEdges];
}

/**
 * Generate recommendations using pre-computed trait vectors.
 * Used when a refined profile (with module signals) is available.
 */
export function generateRecommendationsFromProfile(
  interest: TraitScores,
  aptitude: TraitScores,
): SkillRecommendation[] {
  const profile: TraitProfile = { interest, aptitude };

  const scored = TREE_PROFILES.map((tree) => {
    const interestRaw = dotProduct(profile.interest, tree.traits);
    const aptitudeRaw = dotProduct(profile.aptitude, tree.traits);
    return { tree, interestRaw, aptitudeRaw };
  });

  const interestNorm = normalizeScores(scored.map((s) => s.interestRaw));
  const aptitudeNorm = normalizeScores(scored.map((s) => s.aptitudeRaw));

  const categorized = scored.map((s, i) => {
    const interestScore = interestNorm[i];
    const aptitudeScore = aptitudeNorm[i];
    const totalScore = interestScore + aptitudeScore;

    const highInterest = interestScore > 0.55;
    const highAptitude = aptitudeScore > 0.55;

    let category: RecommendationCategory;
    if (highInterest && highAptitude) {
      category = "strong-match";
    } else if (highAptitude && !highInterest) {
      category = "hidden-potential";
    } else if (highInterest && !highAptitude) {
      category = "growth-edge";
    } else {
      category = "growth-edge";
    }

    return {
      tree: s.tree,
      category,
      interestScore,
      aptitudeScore,
      totalScore,
      reasoning: buildReasoning(s.tree, category, profile),
    };
  });

  const strongMatches = categorized
    .filter((r) => r.category === "strong-match")
    .sort((a, b) => b.totalScore - a.totalScore)
    .slice(0, 3);

  const hiddenPotential = categorized
    .filter((r) => r.category === "hidden-potential")
    .sort((a, b) => b.aptitudeScore - a.aptitudeScore)
    .slice(0, 3);

  const growthEdges = categorized
    .filter((r) => r.category === "growth-edge")
    .sort((a, b) => b.interestScore - a.interestScore)
    .slice(0, 2);

  return [...strongMatches, ...hiddenPotential, ...growthEdges];
}

/**
 * Category labels and descriptions for the results UI.
 */
export const CATEGORY_META: Record<
  RecommendationCategory,
  { label: string; description: string }
> = {
  "strong-match": {
    label: "Strong Matches",
    description: "Skills aligned with both your interests and natural strengths.",
  },
  "hidden-potential": {
    label: "Hidden Potential",
    description:
      "Skills where your natural strengths suggest high potential — even without prior exposure.",
  },
  "growth-edge": {
    label: "Growth Edges",
    description:
      "Skills you're drawn to that would stretch your current abilities.",
  },
};
